### ISSUE TITLE
Calculate open probability

### ISSUE THREAD

**Issue by johiatt** [cs481-ekh/s21-team-ion#28]
References #24 

# Description
When the raw data graph is updated by the user via one of the following:

1. The user loads a new, valid data file
2. The user clicks-and-drags one of the regression boundary lines (updating the regression)
3. The user updates the linear regression via the "Update range" button

Then the open probability should then be calculated so that the open probability graph can be updated.
The formula for calculating the open probability is:

I / I_max

Where I is the current (y-value of the raw data) at a given voltage (x-value of the raw data), and I_max is the linear regression y-value for at the same given voltage.

# Visual representation of I & I_max

![I_over_Imax](https://user-images.githubusercontent.com/16862026/114284153-3934a000-9a0b-11eb-807c-98b9039d36e6.png)

**Comment by vorcepa** [comment]
Closed by previous commit
